version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install front-end
          command: npm run frontend:install
      - run:
          name: Install backend
          command: npm run backend:install
      - run:
          name: Build front-end
          command: npm run frontend:build
      - run:
          name: Build back-end
          command: npm run backend:build
      - run:
          name: Deploy back-End
          command: npm run backend:deploy
      - run:
          name: Deploy front-End
          command: npm run frontend:deploy
workflows:
  Udagram-fullstack-application:
    jobs:
      - build:
        filters:
          branches:
            only:
              - origin